Initial stub out of site layout.
mozilla/nsf-challenge pull request #1
Opened 2017-01-27 17:08 UTC by ScottDowne

@mmmavis the WIP so far.

2017-01-27 17:09 UTC, ScottDowne commented on package.json
> +    "marked": "^0.3.6",
I think I can move these to dev dependencies? Havn't taken a close look yet.

2017-01-31 00:42 UTC, mmmavis commented
@ScottDowne I skimmed through the code just to understand how things work. Things look great 😃 👍 . It needs tweaks here and there but they're mostly minor improvements.

2 slightly bigger things: 
I think we should start using the `classnames` npm package (see [my comment](https://github.com/mozilla/nsf-challenge/pull/1/files#r98574119)) and reduce code repetitions (see [comment](https://github.com/mozilla/nsf-challenge/pull/1/files#r98573191)).

Markdown wise I'd like to defer it to @gvn to review as I don't have any experience setting it up.

2017-01-31 01:04 UTC, gvn commented
Markdown is fine and makes sense for this site given that it's mostly large blocks of non-localized text. 👍

2017-01-31 18:22 UTC, ScottDowne commented on source/js/components/details.js
> +        <Panel activeKey={this.state.activeKey} activateKey={this.onKeyChange} itemKey="item-1" header="How to enter the challenge">
@mmmavis Is it this bit you want generated dynamically?

2017-01-31 19:02 UTC, mmmavis requested changes

2017-01-31 19:02 UTC, mmmavis commented on source/js/components/details.js
> +var React = require(`react`);
`import React from 'react';` ?

2017-01-31 19:02 UTC, mmmavis commented on source/js/components/details.js
> +        </Panel>
There are a bunch of repetitions here. I wonder if we should create an array of objects. Each object just stores values of the `itemKey`, `header`, and `source`. We can then loop through the array using `.map()` to generate the list of `<Panel>`s.

2017-01-31 19:02 UTC, mmmavis commented on source/js/components/sticky-container.js
> +    var className = this.props.className || "";
Let's rely on the [`classnames`](https://github.com/JedWatson/classnames) npm package to handle classnames related stuff. We use this package for many other MoFo sites... it's quite neat!

2017-01-31 19:02 UTC, mmmavis commented on source/pug/partials/nav.pug
> +script(src=`${env.virtualRoot}_js/main.compiled.js`)
Wait do we need to load `main.compiled.js` here as well? 🙄 Loading it in `source/pug/views/home.pug` should be sufficient I suppose.

2017-01-31 19:32 UTC, ScottDowne commented on source/pug/partials/nav.pug
> +script(src=`${env.virtualRoot}_js/main.compiled.js`)
We do not need this, I just missed it.

2017-01-31 19:46 UTC, ScottDowne commented
@mmmavis I believe that's all of them fixed.

2017-01-31 20:06 UTC, mmmavis commented
Thanks @ScottDowne ! Let's fix the Travis error: https://travis-ci.org/mozilla/nsf-challenge/builds/197071170 and have this PR merged so it doesn't grow tooooooo bigggggggggg. 😀

2017-01-31 20:07 UTC, ScottDowne commented
k, done, should be building soon.

2017-02-01 02:38 UTC, ScottDowne commented
@mmmavis finally got this passing.

2017-02-01 18:48 UTC, mmmavis approved these changes
@ScottDowne I think we can merge this one first and tackle rest of the work in followup PRs.

2017-02-01 18:49 UTC, ScottDowne commented
Cool. Feel free to hit merge as I'm afk for a few.

2017-02-01 18:53 UTC, merged