Scroll updates nav links.
mozilla/nsf-challenge pull request #20
Opened 2017-02-06 22:08 UTC by ScottDowne

2017-02-06 22:13 UTC, ScottDowne commented
Fixes https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/34

2017-02-07 21:58 UTC, mmmavis requested changes

2017-02-07 21:58 UTC, mmmavis commented on source/js/components/sticky-nav.js
> +  onScroll: function() {
If it's possible we should not have things hardcoded here. We should be able to get all nav anchors by ```document.querySelectorAll(`.nav-anchor`)``` and get `id` of each element by ```.getAttribute(`id`)```

Also I think this method doesn't belong to `<StickyNav>` as we are not scrolling within the `<StickyNav>` component itself. We should move this to a page wrapper component (if there's any)

2017-02-08 02:07 UTC, mmmavis commented
Um just saw this https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/17#issuecomment-277762999. What do we do if user starts to scroll when a accordion section is open?

2017-02-08 02:10 UTC, ScottDowne commented
I figured it would be an issue but we can land one and fix the other, if it
does in fact conflicts UX wise.

2017-02-08 02:20 UTC, mmmavis commented
I personally don't like "update url with anchor as user scrolls", especially when we have so many anchors on the same page. Let me ask in another repo to get some feedback.

2017-02-08 14:57 UTC, ScottDowne commented on source/js/components/sticky-nav.js
> +  onScroll: function() {
The wrapper for this is main.js. Not a great place to put something that changes the state of another component. Especially if it's not a react component.

I am going to try moving out the scrolling bits a bit to be a bit more separate from the sticky concept. Hopefully that's enough?

2017-02-09 07:24 UTC, mmmavis approved these changes
looks great to me!

2017-02-09 16:30 UTC, merged