scss colour codes cleanup by using $variables
mozilla/nsf-challenge pull request #3
Opened 2017-02-01 20:03 UTC by mmmavis

2017-02-01 20:04 UTC, mmmavis commented
some variables come from mofo-bootstrap: https://mozilla.github.io/mofo-bootstrap/demo/

2017-02-01 20:06 UTC, ScottDowne commented on source/sass/main.scss
> -      background: #fee601;
This is a slightly darker yellow, pulled from https://healthreport.staging.wpengine.com/v01/web-literacy/

2017-02-01 20:08 UTC, ScottDowne requested changes
r-

2017-02-01 20:20 UTC, mmmavis commented
Um I used the color from the Sketch file @kristinashu provided. Either that one is the most up to date color or the color in Sketch file needs to be updated.

2017-02-01 20:25 UTC, mmmavis commented
um wait @ScottDowne the Internet Health Report site **IS** using the same yellow I'm using (same as what the Sketch file uses)

<img width="1418" alt="screen shot 2017-02-01 at 12 23 54 pm" src="https://cloud.githubusercontent.com/assets/2896608/22524744/569184e4-e879-11e6-9ebc-5970fd5b1252.png">

2017-02-01 20:45 UTC, ScottDowne commented
The colour I have an issue with is just on the hover state, not all the colours. You're non hover state colour is correct.

2017-02-01 20:45 UTC, ScottDowne commented
Also, the hover yellow is marginally different. It basically does nothing.

2017-02-01 21:00 UTC, ScottDowne commented on source/sass/main.scss
> -      background: #fee601;
Not the `&:hover` bit, this is a different yellow.

2017-02-01 21:53 UTC, mmmavis commented
@ScottDowne oh ic. PR updated.

2017-02-02 17:56 UTC, ScottDowne approved these changes

2017-02-02 18:43 UTC, merged