A few fixes for image links.
mozilla/nsf-challenge pull request #38
Opened 2017-02-10 20:10 UTC by ScottDowne

2017-02-10 20:37 UTC, mmmavis commented
@ScottDowne I can't seem to find the diff with and without `box-decoration-break: clone;`. Can you attach some screencaps here? Also just a note that the `box-decoration-break` is not very well supported yet (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break))

2017-02-10 20:40 UTC, mmmavis commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
Let's change this to `border-color: darken($nsf-yellow, 10%);` since we are just updating color.

2017-02-10 21:30 UTC, ScottDowne commented
Without clone
![clone2](https://cloud.githubusercontent.com/assets/197334/22844707/7edc1cd0-efad-11e6-99cc-024dc0943b46.png)
with clone
![break](https://cloud.githubusercontent.com/assets/197334/22844708/806ab55c-efad-11e6-91cb-96f2d6f41a84.png)

All it does is maintain margins, padding, border, box shadow, on inline line breaks. It's an enhancement, and it's support is stable chrome and ff, so it has pretty good coverage.

I added it to the events image links too, even though having line breaks there shouldn't happen, given the font sizes I am controlling so it is all on one line. However, unexpected things happen. If it does manage to line break.

2017-02-15 19:58 UTC, mmmavis requested changes

2017-02-15 19:58 UTC, mmmavis commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
Let's change this to `border-color: darken($nsf-yellow, 10%);` since we are just updating color.

2017-02-15 19:58 UTC, mmmavis commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
Can you check through `main.scss` and update other `border: 2px solid darken($nsf-yellow, 10%);` occurrences as well? 👍

2017-02-15 20:00 UTC, mmmavis commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
^ isn't related to the change you made in this PR. Feel free to open another PR to fix this or just use this one.

2017-02-16 19:32 UTC, ScottDowne commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
I was about to do this, then hit a snag (it's a bit more complex). In some cases, it's actually turning a single bottom border, to an all around border on hover, so some are not actually just updating the colour.

We should open a new pull for this, I suspect.

2017-02-20 22:33 UTC, mmmavis commented on source/sass/main.scss
>        border: 2px solid darken($nsf-yellow, 10%);
ah okay, that sounds odd to me. But agreed that it should be tackled in another PR.

2017-02-20 22:33 UTC, mmmavis approved these changes

2017-02-21 17:23 UTC, merged